### ISSUE TITLE
Neeed passwordless setup 

### ISSUE THREAD

**Issue by 0xnryn** [enielrodriguez/conservation-mode-switcher#23]
it requires to put password every single time if anyone know how to fix that please help

**Comment by enielrodriguez** [comment]
> it requires to put password every single time if anyone know how to fix that please help

Hello! Did you try using the suggested command in the general settings?
![300202392-43a55e69-6dc3-4682-9635-b63776d3c077](https://github.com/enielrodriguez/lenovo-conservation-mode-switcher/assets/31964610/5f4d835a-769a-4afe-9879-4bc663d39720)

**Comment by ejnshtein** [comment]
I think this command can be updated to include a description of at least why `%your_group` needs to be replaced.
Like I only knew what to do with this command because I saw this description in [laurento/gnome-shell-extension-ideapad](https://github.com/laurento/gnome-shell-extension-ideapad#:~:text=Depending%20on%20your%20distro%2C%20you%20need%20to%20use%20the%20group%20sudo%20(e.g.%20Debian%20and%20Ubuntu)%20or%20wheel%20(e.g.%20Arch%20and%20Fedora)%20here.%20In%20case%20of%20doubt%2C%20run%20the%20command%20groups%20in%20a%20terminal%20and%20see%20which%20of%20the%20two%20is%20listed%20in%20the%20output.)  and it works great (thank you).
